import localFont from 'next/font/local'
import "./globals.css";

// const noto_sans = Noto_Sans_Bengali({
//   variable: "--font-noto_Bangal",
// })

const noto = localFont({
  src: [
    {
      path: './Font/NotoSansBengali-Black.ttf',
      weight: "900",
      style: ""
    },
    {
      path: './Font/NotoSansBengali-Bold.ttf',
      weight: "700",
      style: ""
    },
    {
      path: './Font/NotoSansBengali-ExtraBold.ttf',
      weight: "800",
      style: ""
    },
    {
      path: './Font/NotoSansBengali-ExtraLight.ttf',
      weight: "200",
      style: ""
    },
    {
      path: './Font/NotoSansBengali-Light.ttf',
      weight: "300",
      style: ""
    },
    {
      path: './Font/NotoSansBengali-Medium.ttf',
      weight: "500",
      style: ""
    },
    {
      path: './Font/NotoSansBengali-Regular.ttf',
      weight: "400",
      style: ""
    },
    {
      path: './Font/NotoSansBengali-SemiBold.ttf',
      weight: "600",
      style: ""
    },
  ],
   variable: "--font-noto",
})

export const metadata = {
  title: "Kalkini Syed Abul Hossen College",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="bn">
      <body
       className={`${noto.variable} font-noto`}
      >
        {children}
      </body>
    </html>
  );
}
